import os
import cv2
import glob
import argparse

from .tracking_pipeline import TrackingPipeline


CONFIG = {
    "IMG_ROOT": "./datasets/raw/DETRAC-Images",

    # Directory containing seqmaps generated by the previous GT script
    "SEQMAP_DIR": "./datasets/trackeval/data/gt/seqmaps",

    # Base path to save tracker results (TrackEval format)
    "TRACKER_OUT_BASE": "./datasets/trackeval/data/trackers",
    "BENCHMARK": "ua-detrac",
    "TRACKER_NAME": "my_tracker",

    "MODEL_PATH": "models/weights/best.pt",
    "CONF": 0.4
}


# =========================
# GET SEQUENCES FROM SEQMAP
# =========================
def get_sequences(split):
    """
    Read the list of sequences from the corresponding seqmap file.
    """
    seqmap_filename = f"{CONFIG['BENCHMARK']}-{split}.txt"
    seqmap_path = os.path.join(CONFIG["SEQMAP_DIR"], seqmap_filename)

    if not os.path.exists(seqmap_path):
        return []

    with open(seqmap_path, "r") as f:
        lines = f.read().strip().splitlines()

    # Skip the "name" header line if it exists
    if lines and lines[0] == "name":
        return lines[1:]

    return lines


# =========================
# RUN ONE SEQUENCE
# =========================
def run_sequence(seq_name, split_name, pipeline):

    image_dir = os.path.join(CONFIG["IMG_ROOT"], seq_name)
    images = sorted(glob.glob(os.path.join(image_dir, "img*.jpg")))

    if len(images) == 0:
        print(f"[WARNING] No images found for sequence: {seq_name}")
        return

    results = []

    for frame_id, img_path in enumerate(images, start=1):

        frame = cv2.imread(img_path)
        if frame is None:
            continue

        det = pipeline.detect(frame)
        tracked = pipeline.track(det)

        if tracked.tracker_id is None:
            continue

        # Extract box coordinates, tracker ID, and predicted class ID
        for box, tid in zip(tracked.xyxy, tracked.tracker_id):

            x1, y1, x2, y2 = box

            # MOT Format: frame, track_id, x, y, w, h, conf, cls, vis
            # Note: conf = 1, visibility = -1 (ignored by TrackEval)
            results.append(
                f"{frame_id},"
                f"{int(tid)},"
                f"{x1:.2f},{y1:.2f},{x2-x1:.2f},{y2-y1:.2f},"
                f"1,1,-1"
            )

    # Create the standard TrackEval output directory structure
    out_dir = os.path.join(
        CONFIG["TRACKER_OUT_BASE"],
        f"{CONFIG['BENCHMARK']}-{split_name}",
        CONFIG["TRACKER_NAME"],
        "data"
    )
    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, f"{seq_name}.txt")

    with open(out_file, "w") as f:
        f.write("\n".join(results))

    print(f"[OK] {split_name} | {seq_name} -> {len(results)} lines")


# =========================
# MAIN
# =========================
def run(split_choice):

    pipeline = TrackingPipeline(
        model_path=CONFIG["MODEL_PATH"],
        conf=CONFIG["CONF"]
    )

    # Determine which splits to run based on user choice
    if split_choice == "all":
        splits = ["val", "test"]
    else:
        splits = [split_choice]

    for split in splits:
        seqs = get_sequences(split)

        if not seqs:
            print(f"\n[SKIP] No data for {split} (Check seqmaps).")
            continue

        print(f"\n=== RUNNING {split} SET ({len(seqs)} seqs) ===")

        for seq in seqs:
            run_sequence(seq, split, pipeline)

    print("\n[DONE] Finished running tracking.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run tracking pipeline.")
    parser.add_argument(
        "--split",
        type=str,
        choices=["val", "test", "all"],
        default="all",
        help="Select split to run: 'val', 'test', or 'all' (default)."
    )

    args = parser.parse_args()
    run(split_choice=args.split)
